# Generated by Django 6.1 on 2026-09-16 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Pascua_App', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pet',
            fields=[
                ('record_id', models.AutoField(primary_key=True, serialize=False)),
                ('pet_name', models.CharField(max_length=100)),
                ('species', models.CharField(max_length=100)),
                ('breed', models.CharField(max_length=100)),
                ('age', models.IntegerField()),
                ('gender', models.CharField(max_length=100)),
                ('owner_name', models.CharField(max_length=100)),
                ('contact_number', models.CharField(max_length=15)),
                ('visit_date', models.DateField()),
                ('medical_notes', models.TextField()),
            ],
        ),
        migrations.DeleteModel(
            name='Product',
        ),
    ]
